// Ol3-Google-Maps. See https://github.com/mapgears/ol3-google-maps/
// License: https://github.com/mapgears/ol3-google-maps/blob/master/LICENSE
// Version: v0.3-12-gca50c71

(function (root, factory) {
    if (typeof exports === "object") {
        module.exports = factory(root.ol);
    } else if (typeof define === "function" && define.amd) {
        define(['ol', 'googlemaps'], factory);
    } else {
        root.olgm = factory(root.ol);
    }
}(this, function (ol) {
    var OL3GOOGLEMAPS = {};
    var g, l = this;
    function n(a) {
        var b = typeof a; if ("object" == b) if (a) { if (a instanceof Array) return "array"; if (a instanceof Object) return b; var c = Object.prototype.toString.call(a); if ("[object Window]" == c) return "object"; if ("[object Array]" == c || "number" == typeof a.length && "undefined" != typeof a.splice && "undefined" != typeof a.propertyIsEnumerable && !a.propertyIsEnumerable("splice")) return "array"; if ("[object Function]" == c || "undefined" != typeof a.call && "undefined" != typeof a.propertyIsEnumerable && !a.propertyIsEnumerable("call")) return "function" } else return "null"; else if ("function" ==
        b && "undefined" == typeof a.call) return "object"; return b
    } function aa(a, b, c) { return a.call.apply(a.bind, arguments) } function ba(a, b, c) { if (!a) throw Error(); if (2 < arguments.length) { var d = Array.prototype.slice.call(arguments, 2); return function () { var c = Array.prototype.slice.call(arguments); Array.prototype.unshift.apply(c, d); return a.apply(b, c) } } return function () { return a.apply(b, arguments) } }
    function p(a, b, c) { p = Function.prototype.bind && -1 != Function.prototype.bind.toString().indexOf("native code") ? aa : ba; return p.apply(null, arguments) } function q(a, b) { var c = a.split("."), d = OL3GOOGLEMAPS || l; c[0] in d || !d.execScript || d.execScript("var " + c[0]); for (var e; c.length && (e = c.shift()) ;) c.length || void 0 === b ? d[e] ? d = d[e] : d = d[e] = {} : d[e] = b }
    function s(a, b) { function c() { } c.prototype = b.prototype; a.j = b.prototype; a.prototype = new c; a.da = function (a, c, f) { return b.prototype[c].apply(a, Array.prototype.slice.call(arguments, 2)) } }; function t(a, b) { this.e = a; this.a = b }; function u(a, b) { return a < b ? -1 : a > b ? 1 : 0 }; var v = Array.prototype, ca = v.indexOf ? function (a, b, c) { return v.indexOf.call(a, b, c) } : function (a, b, c) { c = null == c ? 0 : 0 > c ? Math.max(0, a.length + c) : c; if ("string" == typeof a) return "string" == typeof b && 1 == b.length ? a.indexOf(b, c) : -1; for (; c < a.length; c++) if (c in a && a[c] === b) return c; return -1 }; var x; a: { var z = l.navigator; if (z) { var A = z.userAgent; if (A) { x = A; break a } } x = "" }; var B = -1 != x.indexOf("Opera") || -1 != x.indexOf("OPR"), C = -1 != x.indexOf("Trident") || -1 != x.indexOf("MSIE"), D = -1 != x.indexOf("Gecko") && -1 == x.toLowerCase().indexOf("webkit") && !(-1 != x.indexOf("Trident") || -1 != x.indexOf("MSIE")), E = -1 != x.toLowerCase().indexOf("webkit"); function F() { var a = l.document; return a ? a.documentMode : void 0 }
    var G = function () { var a = "", b; if (B && l.opera) return a = l.opera.version, "function" == n(a) ? a() : a; D ? b = /rv\:([^\);]+)(\)|;)/ : C ? b = /\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/ : E && (b = /WebKit\/(\S+)/); b && (a = (a = b.exec(x)) ? a[1] : ""); return C && (b = F(), b > parseFloat(a)) ? String(b) : a }(), da = {};
    function H(a) {
        var b; if (!(b = da[a])) {
            b = 0; for (var c = String(G).replace(/^[\s\xa0]+|[\s\xa0]+$/g, "").split("."), d = String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g, "").split("."), e = Math.max(c.length, d.length), f = 0; 0 == b && f < e; f++) {
                var h = c[f] || "", k = d[f] || "", w = RegExp("(\\d*)(\\D*)", "g"), m = RegExp("(\\d*)(\\D*)", "g"); do {
                    var r = w.exec(h) || ["", "", ""], y = m.exec(k) || ["", "", ""]; if (0 == r[0].length && 0 == y[0].length) break; b = u(0 == r[1].length ? 0 : parseInt(r[1], 10), 0 == y[1].length ? 0 : parseInt(y[1], 10)) || u(0 == r[2].length, 0 == y[2].length) ||
                    u(r[2], y[2])
                } while (0 == b)
            } b = da[a] = 0 <= b
        } return b
    } var ea = l.document, fa = ea && C ? F() || ("CSS1Compat" == ea.compatMode ? parseInt(G, 10) : 5) : void 0; var I; (I = !C) || (I = C && 9 <= fa); var ga = I, ha = C && !H("9"); !E || H("528"); D && H("1.9b") || C && H("8") || B && H("9.5") || E && H("528"); D && !H("8") || C && H("9"); function J(a, b) { this.type = a; this.a = this.b = b } J.prototype.c = function () { }; function K(a) { K[" "](a); return a } K[" "] = function () { }; function L(a, b) { J.call(this, a ? a.type : ""); this.d = this.a = this.b = null; if (a) { this.type = a.type; this.b = a.target || a.srcElement; this.a = b; var c = a.relatedTarget; if (c && D) try { K(c.nodeName) } catch (d) { } this.d = a; a.defaultPrevented && this.c() } } s(L, J); L.prototype.c = function () { L.j.c.call(this); var a = this.d; if (a.preventDefault) a.preventDefault(); else if (a.returnValue = !1, ha) try { if (a.ctrlKey || 112 <= a.keyCode && 123 >= a.keyCode) a.keyCode = -1 } catch (b) { } }; var ia = "closure_listenable_" + (1E6 * Math.random() | 0), ja = 0; function ka(a, b, c, d, e) { this.p = a; this.a = null; this.src = b; this.type = c; this.B = !!d; this.b = e; ++ja; this.s = this.A = !1 } function la(a) { a.s = !0; a.p = null; a.a = null; a.src = null; a.b = null }; function ma(a) { this.src = a; this.a = {}; this.b = 0 }; var M = "closure_lm_" + (1E6 * Math.random() | 0), N = {}, na = 0;
    function oa(a, b, c, d, e) {
        if ("array" == n(b)) { for (var f = 0; f < b.length; f++) oa(a, b[f], c, d, e); return null } c = pa(c); if (a && a[ia]) a = a.a(b, c, d, e); else {
            f = c; if (!b) throw Error("Invalid event type"); c = !!d; var h = O(a); h || (a[M] = h = new ma(a)); var k = h, w = b.toString(), h = k.a[w]; h || (h = k.a[w] = [], k.b++); var m; b: { for (m = 0; m < h.length; ++m) { var r = h[m]; if (!r.s && r.p == f && r.B == !!d && r.b == e) break b } m = -1 } -1 < m ? (d = h[m], d.A = !1) : (d = new ka(f, k.src, w, !!d, e), d.A = !1, h.push(d)); d.a || (e = qa(), d.a = e, e.src = a, e.p = d, a.addEventListener ? a.addEventListener(b.toString(),
            e, c) : a.attachEvent(ra(b.toString()), e), na++); a = d
        } return a
    } function qa() { var a = sa, b = ga ? function (c) { return a.call(b.src, b.p, c) } : function (c) { c = a.call(b.src, b.p, c); if (!c) return c }; return b } function ra(a) { return a in N ? N[a] : N[a] = "on" + a } function ta(a, b, c, d) { var e = 1; if (a = O(a)) if (b = a.a[b.toString()]) for (b = b.concat(), a = 0; a < b.length; a++) { var f = b[a]; f && f.B == c && !f.s && (e &= !1 !== ua(f, d)) } return Boolean(e) }
    function ua(a, b) { var c = a.p, d = a.b || a.src; if (a.A && "number" != typeof a && a && !a.s) { var e = a.src; if (e && e[ia]) e.ea(a); else { var f = a.type, h = a.a; e.removeEventListener ? e.removeEventListener(f, h, a.B) : e.detachEvent && e.detachEvent(ra(f), h); na--; if (f = O(e)) { h = a.type; if (h in f.a) { var k = f.a[h], w = ca(k, a), m; (m = 0 <= w) && v.splice.call(k, w, 1); m && (la(a), 0 == f.a[h].length && (delete f.a[h], f.b--)) } 0 == f.b && (f.src = null, e[M] = null) } else la(a) } } return c.call(d, b) }
    function sa(a, b) {
        if (a.s) return !0; if (!ga) { var c; if (!(c = b)) a: { c = ["window", "event"]; for (var d = l, e; e = c.shift() ;) if (null != d[e]) d = d[e]; else { c = null; break a } c = d } e = c; c = new L(e, this); d = !0; if (!(0 > e.keyCode || void 0 != e.returnValue)) { a: { var f = !1; if (0 == e.keyCode) try { e.keyCode = -1; break a } catch (h) { f = !0 } if (f || void 0 == e.returnValue) e.returnValue = !0 } e = []; for (f = c.a; f; f = f.parentNode) e.push(f); for (var f = a.type, k = e.length - 1; 0 <= k; k--) c.a = e[k], d &= ta(e[k], f, !0, c); for (k = 0; k < e.length; k++) c.a = e[k], d &= ta(e[k], f, !1, c) } return d } return ua(a,
        new L(b, this))
    } function O(a) { a = a[M]; return a instanceof ma ? a : null } var va = "__closure_events_fn_" + (1E9 * Math.random() >>> 0); function pa(a) { return "function" == n(a) ? a : a[va] || (a[va] = function (b) { return a.handleEvent(b) }) }; var wa = [156543.03390625, 78271.516953125, 39135.7584765625, 19567.87923828125, 9783.939619140625, 4891.9698095703125, 2445.9849047851562, 1222.9924523925781, 611.4962261962891, 305.74811309814453, 152.87405654907226, 76.43702827453613, 38.218514137268066, 19.109257068634033, 9.554628534317017, 4.777314267158508, 2.388657133579254, 1.194328566789627, .5971642833948135, .298582141697, .14929107084, .07464553542, .03732276771];
    function xa(a) { var b = null; return b = a instanceof ol.geom.Point ? a.getCoordinates() : a instanceof ol.geom.Polygon ? a.getInteriorPoint().getCoordinates() : ol.extent.getCenter(a.getExtent()) } function P(a) { var b = "", c = null; "string" === typeof a ? 0 === a.indexOf("rgba") ? c = ya(a) : b = a : c = a; null !== c && (b = ["rgb(", c[0], ",", c[1], ",", c[2], ")"].join("")); return b } function Q(a) { var b = null, c = null; "string" === typeof a ? 0 === a.indexOf("rgba") && (c = ya(a)) : c = a; c && void 0 !== c[3] && (b = +c[3]); return b }
    function za(a) { var b = null; a instanceof ol.style.Style ? b = a : a instanceof ol.layer.Vector || a instanceof ol.Feature ? (b = a.getStyle()) && b instanceof Function && (b = b()[0]) : a instanceof Function && (b = a()[0]); return b } function ya(a) { var b = null; (a = a.match(/^rgba?\((\d+),\s*(\d+),\s*(\d+)(?:,\s*(\d+(?:\.\d+)?))?\)$/)) && a.length && (b = [+a[1], +a[2], +a[3], +a[4]]); return b } function R(a) { a.forEach(ol.Observable.unByKey); a.length = 0 }; function S(a) { this.set("font", "normal 10px sans-serif"); this.set("textAlign", "center"); this.set("textBaseline", "middle"); this.set("zIndex", 1E3); this.setValues(a) } s(S, google.maps.OverlayView); g = S.prototype; g.J = !1; g.L = 0; g.T = 0; g.changed = function (a) { switch (a) { case "fontColor": case "fontFamily": case "fontSize": case "fontWeight": case "strokeColor": case "strokeWeight": case "text": case "textAlign": case "textBaseline": Aa(this); break; case "maxZoom": case "minZoom": case "offsetX": case "offsetY": case "position": this.draw() } };
    function Aa(a) { var b = a.a; if (b) { var c = b.style, d = a.get("fontColor"); if (d && (c.zIndex = a.get("zIndex"), c = b.getContext("2d"), c.clearRect(0, 0, b.width, b.height), c.textBaseline = a.get("textBaseline"), c.strokeStyle = a.get("strokeColor"), c.fillStyle = d, c.font = a.get("font"), c.textAlign = a.get("textAlign"), d = a.get("text"))) { var e = b.width / 2, b = b.height / 2; if (a = Number(a.get("strokeWeight"))) c.lineWidth = a, c.strokeText(d, e, b); c.fillText(d, e, b) } } }
    g.onAdd = function () { var a = this.a = document.createElement("canvas"); a.style.position = "absolute"; a.getContext("2d").lineJoin = "round"; Aa(this); var b = this.getPanes(); b && b.markerLayer.appendChild(a) }; g.draw = function () { if (this.J) Ba(this); else { var a = this.a; if (a) { var a = a.getContext("2d"), b = a.canvas.height; this.T = a.canvas.width; this.L = b; Ba(this) && (this.J = !0) } } };
    function Ba(a) { var b = a.get("position"); if (!b) return !1; var c = a.getProjection(); if (!c) return !1; var c = c.fromLatLngToDivPixel(b), d = a.L, e = a.T, f = a.get("offsetX") || 0, h = a.get("offsetY") || 0, b = a.a.style; b.top = c.y - d / 2 + h + "px"; b.left = c.x - e / 2 + f + "px"; c = a.get("minZoom"); d = a.get("maxZoom"); void 0 === c && void 0 === d ? a = "" : (a = a.getMap()) ? (a = a.getZoom(), a = a < c || a > d ? "hidden" : "") : a = ""; b.visibility = a; return !0 } g.onRemove = function () { var a = this.a; a && a.parentNode && a.parentNode.removeChild(a) }; function Ca(a, b) {
        var c = null; if (a instanceof ol.geom.Point) c = T(a, b); else if (a instanceof ol.geom.LineString || a instanceof ol.geom.Polygon) {
            var d = void 0 !== b ? b.getView().getProjection() : "EPSG:3857", c = [], e, f; f = a instanceof ol.geom.LineString ? a.getCoordinates() : a.getCoordinates()[0]; for (var h = 0, k = f.length; h < k; h++) e = ol.proj.transform(f[h], d, "EPSG:4326"), c.push(new google.maps.LatLng(e[1], e[0])); d = null; a instanceof ol.geom.LineString ? d = new google.maps.Data.LineString(c) : d = new google.maps.Data.Polygon([c]);
            c = d
        } return c
    } function T(a, b) { var c = void 0 !== b ? b.getView().getProjection() : "EPSG:3857", d; d = a instanceof ol.geom.Point ? a.getCoordinates() : a; c = ol.proj.transform(d, c, "EPSG:4326"); return new google.maps.LatLng(c[1], c[0]) }
    function Da(a, b) {
        var c = null, d = za(a); if (d) {
            var c = {}, e = d.getStroke(); if (e) { var f = e.getColor(); f && (c.strokeColor = P(f), f = Q(f), null !== f && (c.strokeOpacity = f)); (e = e.getWidth()) && (c.strokeWeight = e) } if (e = d.getFill()) if (e = e.getColor()) c.fillColor = P(e), e = Q(e), null !== e && (c.fillOpacity = e); if (f = d.getImage()) {
                d = {}; e = {}; if (f instanceof ol.style.Circle) {
                    e.path = google.maps.SymbolPath.CIRCLE; var h = f.getStroke(); if (h) { var k = h.getColor(); k && (e.strokeColor = P(k)); e.strokeWeight = h.getWidth() } if (h = f.getFill()) if (h = h.getColor()) e.fillColor =
                    P(h), h = Q(h), e.fillOpacity = null !== h ? h : 1; (f = f.getRadius()) && (e.scale = f)
                } else f instanceof ol.style.Icon && ((h = f.getSrc()) && (e.url = h), h = f.getScale(), (k = f.getAnchor()) && (e.anchor = void 0 !== h ? new google.maps.Point(k[0] * h, k[1] * h) : new google.maps.Point(k[0], k[1])), (k = f.getOrigin()) && (e.origin = new google.maps.Point(k[0], k[1])), f = f.getSize()) && (e.size = new google.maps.Size(f[0], f[1]), void 0 !== h && (e.scaledSize = new google.maps.Size(f[0] * h, f[1] * h))); Object.keys(d).length ? c.icon = d : Object.keys(e).length && (c.icon =
                e)
            } 0 === Object.keys(c).length ? c.visible = !1 : void 0 !== b && (c.zIndex = 2 * b)
        } return c
    }; function U(a, b) { this.h = []; t.call(this, a, b) } s(U, t); U.prototype.g = function () { }; U.prototype.f = function () { R(this.h) }; function V(a, b, c, d, e) { this.b = c; this.d = d; this.i = e; U.call(this, a, b) } s(V, U); g = V.prototype; g.n = null; g.k = null;
    g.g = function () {
        V.j.g.call(this); var a = this.b.getGeometry(), b = this.b.getGeometry(), b = Ca(b, void 0); this.n = new google.maps.Data.Feature({ geometry: b }); this.d.add(this.n); (b = Da(this.b, this.i)) && this.d.overrideStyle(this.n, b); if (b = za(this.b)) {
            var c = b.getText(); if (c) {
                var b = { align: "center", position: T(xa(a)), zIndex: 2 * this.i + 1 }, d = c.getText(); d && (b.text = d); (d = c.getFont()) && (b.font = d); (d = c.getFill()) && (d = d.getColor()) && (b.fontColor = d); if (d = c.getStroke()) {
                    var e = d.getColor(); e && (b.strokeColor = e); (d = d.getWidth()) &&
                    (b.strokeWeight = d)
                } (d = c.getOffsetX()) && (b.offsetX = d); (d = c.getOffsetY()) && (b.offsetY = d); (d = c.getTextAlign()) && (b.textAlign = d); (c = c.getTextBaseline()) && (b.textBaseline = c); this.k = new S(b); this.k.setMap(this.a)
            }
        } b = this.h; this.c = a.on("change", this.F, this); b.push(this.c); b.push(this.b.on("change:" + this.b.getGeometryName(), this.V, this))
    }; g.f = function () { this.d.remove(this.n); this.n = null; this.k && (this.k.setMap(null), this.k = null); V.j.f.call(this) };
    g.F = function () { var a = this.b.getGeometry(); this.n.setGeometry(Ca(a)); this.k && (a = T(xa(a)), this.k.set("position", a)) }; g.V = function () { var a = this.h; ol.Observable.unByKey(this.c); a.splice(a.indexOf(this.c), 1); this.c = this.b.getGeometry().on("change", this.F, this); a.push(this.c); this.F() }; function W(a, b, c, d) { this.b = []; this.d = []; this.i = d; this.c = c; U.call(this, a, b) } s(W, U); g = W.prototype; g.g = function () { W.j.g.call(this); this.c.getFeatures().forEach(this.R, this); var a = this.h; a.push(this.c.on("addfeature", this.U, this)); a.push(this.c.on("removefeature", this.Y, this)) }; g.f = function () { this.c.getFeatures().forEach(this.P, this); W.j.f.call(this) }; g.U = function (a) { this.R(a.feature) }; g.Y = function (a) { this.P(a.feature) };
    g.R = function (a) { var b = this.e, c = this.a, d = this.i; this.b.push(a); b = new V(b, c, a, d, this.b.indexOf(a)); b.g(); this.d.push({ feature: a, r: b }) }; g.P = function (a) { a = this.b.indexOf(a); -1 !== a && (this.b.splice(a, 1), this.d[a].r.f(), this.d.splice(a, 1)) }; function X(a, b) { U.call(this, a, b) } s(X, U); g = X.prototype; g.v = null; g.g = function () { X.j.g.call(this); var a = this.e.getView(), b = this.h; b.push(a.on("change:center", this.u, this)); b.push(a.on("change:resolution", this.H, this)); b.push(oa(window, "resize", this.$, !1, this)); this.u(); this.H() }; g.f = function () { X.j.f.call(this) }; g.u = function () { var a = this.e.getView(), b = a.getProjection(), a = a.getCenter(); "array" == n(a) && (a = ol.proj.transform(a, b, "EPSG:4326"), this.a.setCenter(new google.maps.LatLng(a[1], a[0]))) };
    g.H = function () { var a = this.e.getView().getResolution(); if ("number" == typeof a) { var b; b = null; for (var a = Math.round(1E3 * a) / 1E3, c = 0, d = wa.length; c < d; c++) if (a == Math.round(1E3 * wa[c]) / 1E3) { b = c; break } null !== b && this.a.setZoom(b) } }; g.$ = function () { null === this.v || l.clearTimeout(this.v); this.v = window.setTimeout(p(this.ca, this), 100) }; g.ca = function () { this.u(); this.v = null }; function Y(a) { a = void 0 !== a ? a : {}; ol.layer.Group.call(this, a); this.a = void 0 !== a.mapTypeId ? a.mapTypeId : google.maps.MapTypeId.ROADMAP; this.c = a.styles ? a.styles : null } s(Y, ol.layer.Group); Y.prototype.b = function () { return this.a }; function Z(a, b, c) { this.t = []; this.C = []; this.b = []; this.D = []; this.i = new X(a, b); this.M = c; this.K = b.getDiv(); this.c = a.getViewport(); this.d = a.getTargetElement(); U.call(this, a, b); if (this.e.getView().getCenter()) this.e.once("postrender", function () { this.G = !0; this.q() }, this); else this.e.getView().once("change:center", function () { this.e.once("postrender", function () { this.G = !0; this.q() }, this); this.q() }, this) } s(Z, U); g = Z.prototype; g.o = !1; g.G = !1;
    g.g = function () { Z.j.g.call(this); var a = this.e.getLayers(); a.forEach(this.S, this); var b = this.h; b.push(a.on("add", this.W, this)); b.push(a.on("remove", this.X, this)) }; g.f = function () { this.e.getLayers().forEach(this.Q, this); Z.j.f.call(this) }; g.W = function (a) { this.S(a.element) }; g.X = function (a) { this.Q(a.element) };
    g.S = function (a) { if (a instanceof Y) this.t.push(a), this.C.push({ layer: a, h: [a.on("change:visible", this.q, this)] }), this.q(); else if (a instanceof ol.layer.Vector && this.M) { var b = this.e, c = this.a, d = a.getSource(); if (d) { this.D.push(a); var e = new google.maps.Data({ map: c }), f = Da(a); f && e.setStyle(f); b = new W(b, c, d, e); c = a.getOpacity(); e = { data: e, r: b, layer: a, h: [], opacity: c }; e.h.push(a.on("change:visible", this.Z.bind(this, e), this)); this.w(e); this.b.push(e) } } };
    g.Q = function (a) { if (a instanceof Y) a = this.t.indexOf(a), -1 !== a && (this.t.splice(a, 1), R(this.C[a].h), this.C.splice(a, 1), this.q()); else if (a instanceof ol.layer.Vector && this.M) { var b = this.D.indexOf(a); if (-1 !== b) { this.D.splice(b, 1); var c = this.b[b]; R(c.h); c.data.setMap(null); c.r.f(); a.setOpacity(c.opacity); this.b.splice(b, 1) } } };
    function Ea(a) { var b = a.e.getView().getCenter(); !a.o && a.G && b && (a.d.removeChild(a.c), a.d.appendChild(a.K), a.a.controls[google.maps.ControlPosition.TOP_LEFT].push(a.c), a.i.g(), google.maps.event.trigger(a.a, "resize"), a.i.u(), a.i.H(), a.o = !0, a.b.forEach(a.w, a)) }
    g.q = function () {
        var a = null; this.e.getLayers().getArray().slice(0).reverse().every(function (b) { return b instanceof Y && b.getVisible() && -1 !== this.t.indexOf(b) ? (a = b, !1) : !0 }, this); if (a) { this.a.setMapTypeId(a.a); var b = a.c; b ? this.a.setOptions({ styles: b }) : this.a.setOptions({ styles: null }); Ea(this) } else this.o && (this.a.controls[google.maps.ControlPosition.TOP_LEFT].removeAt(0), this.d.removeChild(this.K), this.d.appendChild(this.c), this.i.f(), this.c.style.position = "relative", this.b.forEach(this.I, this), this.o =
        !1)
    }; g.w = function (a) { a.layer.getVisible() && this.o && (a.r.g(), a.layer.setOpacity(0)) }; g.I = function (a) { a.r.f(); a.layer.setOpacity(a.opacity) }; g.Z = function (a) { a.layer.getVisible() ? this.w(a) : this.I(a) }; function $(a) { this.b = []; var b = document.createElement("div"); b.style.height = "inherit"; b.style.width = "inherit"; b = new google.maps.Map(b, { disableDefaultUI: !0, disableDoubleClickZoom: !0, draggable: !1, keyboardShortcuts: !1, mapTypeId: google.maps.MapTypeId.ROADMAP, scrollwheel: !1, streetViewControl: !1 }); t.call(this, a.map, b); this.c = new Z(this.e, this.a, void 0 !== a.watchVector ? a.watchVector : !0); this.b.push(this.c) } s($, t); g = $.prototype; g.l = !1;
    g.N = function () { if (!this.l) { for (var a = 0, b = this.b.length; a < b; a++) this.b[a].g(); this.l = !0 } }; g.O = function () { if (this.l) { for (var a = 0, b = this.b.length; a < b; a++) this.b[a].f(); this.l = !1 } }; g.aa = function () { return this.l && this.c.o }; g.ba = function () { this.l ? this.O() : this.N() }; q("olgm.OLGoogleMaps", $); $.prototype.activate = $.prototype.N; $.prototype.deactivate = $.prototype.O; $.prototype.getGoogleMapsActive = $.prototype.aa; $.prototype.toggle = $.prototype.ba; q("olgm.layer.Google", Y); Y.prototype.getMapTypeId = Y.prototype.b; q("olgm.interaction.defaults", function (a) { a = void 0 !== a ? a : {}; a.altShiftDragRotate = !1; a.dragPan = !1; a.pinchRotate = !1; return ol.interaction.defaults(a).extend([new ol.interaction.DragPan]) }); q("olgm.gm.MapLabel", S); S.prototype.changed = S.prototype.changed;
    S.prototype.onAdd = S.prototype.onAdd; S.prototype.draw = S.prototype.draw; S.prototype.onRemove = S.prototype.onRemove;
    return OL3GOOGLEMAPS.olgm;
}));
